C:\Users\tcastilho\source\repos\CodeQLExample\codeql-runner\codeql_databases\log\build-tracer.log
3
**\moles*.exe
<null>
10
0
0
**\fakes*.exe
<null>
10
0
0
**\csc*.exe
C:\Users\tcastilho\codeql-runner-tools\CodeQL\0.0.0-20210909\x64\codeql\csharp\tools\win64\Semmle.Extraction.CSharp.Driver.exe
0
3
--compiler
"${compiler}"
--cil
0